name: remixicon
description: Remix icon is a set of open-source neutral-style system symbols elaborately crafted for designers and developers.
version: 1.3.1
homepage: https://remixicon.com/
repository: https://github.com/alialnaghmoush/remixicon
topics: [icon]

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Remix
      fonts:
        - asset: fonts/Remix.ttf

screenshots:
  - description: The Remix Icon logo.
    path: images/remixIconLogo.png
